version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    # build: .
    image: node:16
    # image: clean-node-api
    restart: always
    working_dir: /usr/src/clean-node-api
    # command: npm run debug
    command: bash -c "npm install --omit=dev && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    depends_on:
      - mongo
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo